"""
netzwerk/nachrichten.py - Nachrichtentypen als Konstanten

Abhängigkeiten: keine externen Dependencies
"""

VERBINDUNG_HERSTELLEN = "verbindung_herstellen"
VERBINDUNG_BESTAETIGT = "verbindung_bestaetigt"
VERBINDUNG_GETRENNT = "verbindung_getrennt"
FEHLER = "fehler"

REGISTRIEREN = "registrieren"
REGISTRIEREN_ERFOLG = "registrieren_erfolg"
REGISTRIEREN_FEHLER = "registrieren_fehler"
LOGIN = "login"
LOGIN_ERFOLG = "login_erfolg"
LOGIN_FEHLER = "login_fehler"
LOGOUT = "logout"

SCHLUESSEL_TYP = "typ"
SCHLUESSEL_DATEN = "daten"
SCHLUESSEL_FEHLER = "fehler"
SCHLUESSEL_BENUTZERNAME = "benutzername"
SCHLUESSEL_PASSWORT = "passwort"
SCHLUESSEL_SPIELER_ID = "spieler_id"
SCHLUESSEL_NACHRICHT = "nachricht"

CHARAKTERE_LADEN = "charaktere_laden"
CHARAKTERE_ANTWORT = "charaktere_antwort"
CHARAKTER_ERSTELLEN = "charakter_erstellen"
CHARAKTER_ERSTELLT = "charakter_erstellt"
CHARAKTER_ERSTELLEN_FEHLER = "charakter_erstellen_fehler"
CHARAKTER_WAEHLEN = "charakter_waehlen"
CHARAKTER_GEWAEHLT = "charakter_gewaehlt"

SCHLUESSEL_CHARAKTERE = "charaktere"
SCHLUESSEL_CHARAKTER_ID = "charakter_id"
SCHLUESSEL_CHARAKTER_NAME = "charakter_name"
SCHLUESSEL_MASTERIE = "masterie"
SCHLUESSEL_STATS = "stats"

CHARAKTER_DETAILS_LADEN = "charakter_details_laden"
CHARAKTER_DETAILS_ANTWORT = "charakter_details_antwort"

SCHLUESSEL_CHARAKTER_DATEN = "charakter_daten"

TESTKAMPF_STARTEN = "testkampf_starten"
KAMPF_ERGEBNIS = "kampf_ergebnis"

SCHLUESSEL_KAMPF_ERGEBNIS = "kampf_ergebnis"

QUESTS_LADEN = "quests_laden"
QUESTS_ANTWORT = "quests_antwort"
QUEST_ANNEHMEN = "quest_annehmen"
QUEST_ANGENOMMEN = "quest_angenommen"
QUEST_AUFLOESEN = "quest_aufloesen"
QUEST_TIMER_REDUZIEREN = "quest_timer_reduzieren"
QUEST_TIMER_REDUZIERT = "quest_timer_reduziert"
QUEST_ERGEBNIS = "quest_ergebnis"

SCHLUESSEL_QUESTS = "quests"
SCHLUESSEL_QUEST_ID = "quest_id"
SCHLUESSEL_QUEST_ERGEBNIS = "quest_ergebnis"

INVENTAR_LADEN = "inventar_laden"
INVENTAR_ANTWORT = "inventar_antwort"
SCHLUESSEL_ITEMS = "items"

ITEM_AUSRUESTEN = "item_ausruesten"
ITEM_ABLEGEN = "item_ablegen"
SCHLUESSEL_ITEM_ID = "item_id"
SCHLUESSEL_SLOT = "slot"

SKILLS_LADEN = "skills_laden"
SKILLS_ANTWORT = "skills_antwort"
SKILL_BAUM_LADEN = "skill_baum_laden"
SKILL_BAUM_ANTWORT = "skill_baum_antwort"
SKILL_PUNKT_INVESTIEREN = "skill_punkt_investieren"
SKILL_PUNKT_INVESTIERT = "skill_punkt_investiert"
SKILL_AUSRUESTEN = "skill_ausruesten"
SKILL_AUSGERUESTET = "skill_ausgeruestet"
SKILL_ABLEGEN = "skill_ablegen"
SKILL_ABGELEGT = "skill_abgelegt"

SCHLUESSEL_SKILL_ID = "skill_id"
SCHLUESSEL_SKILL_SLOT = "skill_slot"
SCHLUESSEL_SKILLS = "skills"
SCHLUESSEL_SKILL_BAEUME = "skill_baeume"
SCHLUESSEL_MASTERIE_BAUM = "masterie_baum"

KLASSEN_LADEN = "klassen_laden"
KLASSEN_ANTWORT = "klassen_antwort"
KLASSEN_INIT = "klassen_init"

SPEZIALISIERUNG_WAEHLEN = "spezialisierung_waehlen"
SPEZIALISIERUNG_GEWAEHLT = "spezialisierung_gewaehlt"

NODE_SKILLEN = "node_skillen"
NODE_GESKILLT = "node_geskillt"

SCHLUESSEL_NODE_ID = "node_id"
SCHLUESSEL_KLASSEN_ID = "klassen_id"
SCHLUESSEL_STUFE = "stufe"

REISE_STARTEN = "reise_starten"
REISE_GESTARTET = "reise_gestartet"
REISE_BEENDEN = "reise_beenden"
REISE_BEENDET = "reise_beendet"
REISE_STATUS_LADEN = "reise_status_laden"
REISE_STATUS_ANTWORT = "reise_status_antwort"
REISE_BELOHNUNGEN_LADEN = "reise_belohnungen_laden"
REISE_BELOHNUNGEN_ANTWORT = "reise_belohnungen_antwort"
REISE_BELOHNUNGEN_ABHOLEN = "reise_belohnungen_abholen"
REISE_BELOHNUNGEN_ABGEHOLT = "reise_belohnungen_abgeholt"

SCHLUESSEL_REISE_ID = "reise_id"
SCHLUESSEL_KAMPF_ERGEBNISSE = "kampf_ergebnisse"
SCHLUESSEL_GESAMT_GOLD = "gesamt_gold"
SCHLUESSEL_GESAMT_XP = "gesamt_xp"
SCHLUESSEL_ANZAHL_QUESTS = "anzahl_quests"

SHOP_LADEN = "shop_laden"
SHOP_ANTWORT = "shop_antwort"
SHOP_REROLL = "shop_reroll"
SHOP_REROLL_ANTWORT = "shop_reroll_antwort"
SHOP_KAUFEN = "shop_kaufen"
SHOP_GEKAUFT = "shop_gekauft"
SHOP_KAUFEN_FEHLER = "shop_kaufen_fehler"
TRANK_KAUFEN = "trank_kaufen"
TRANK_GEKAUFT = "trank_gekauft"
TRANK_KAUFEN_FEHLER = "trank_kaufen_fehler"

TRANK_ENTFERNEN = "trank_entfernen"
TRANK_ENTFERNT = "trank_entfernt"

SCHLUESSEL_TRANK_ID = "trank_id"
SCHLUESSEL_TRANK_STAT = "trank_stat"
SCHLUESSEL_TRANK_STUFE = "trank_stufe"
SCHLUESSEL_TRAENKE = "traenke"
SCHLUESSEL_SHOP_SLOT = "shop_slot"
SCHLUESSEL_ANGEBOTE = "angebote"
SCHLUESSEL_AKTIVE_TRAENKE = "aktive_traenke"

ARENA_LADEN = "arena_laden"
ARENA_ANTWORT = "arena_antwort"
ARENA_KAMPF_STARTEN = "arena_kampf_starten"
ARENA_KAMPF_ERGEBNIS = "arena_kampf_ergebnis"
ARENA_SHOP_KAUFEN = "arena_shop_kaufen"
ARENA_SHOP_GEKAUFT = "arena_shop_gekauft"
ARENA_SHOP_KAUFEN_FEHLER = "arena_shop_kaufen_fehler"
ARENA_VERZAUBERN = "arena_verzaubern"
ARENA_VERZAUBERT = "arena_verzaubert"

GILDE_LADEN = "gilde_laden"
GILDE_ANTWORT = "gilde_antwort"
GILDE_ERSTELLEN = "gilde_erstellen"
GILDE_ERSTELLT = "gilde_erstellt"
GILDE_BEITRETEN = "gilde_beitreten"
GILDE_BEIGETRETEN = "gilde_beigetreten"
GILDE_VERLASSEN = "gilde_verlassen"
GILDE_VERLASSEN_OK = "gilde_verlassen_ok"
GILDE_STEUER_SETZEN = "gilde_steuer_setzen"
GILDE_STEUER_OK = "gilde_steuer_ok"
GILDE_RANG_SETZEN = "gilde_rang_setzen"
GILDE_RANG_OK = "gilde_rang_ok"
GILDE_KICK = "gilde_kick"
GILDE_KICK_OK = "gilde_kick_ok"
GILDE_AUFSTEIGEN = "gilde_aufsteigen"
GILDE_AUFGESTIEGEN = "gilde_aufgestiegen"

SCHLUESSEL_GEGNER_ID = "gegner_id"
SCHLUESSEL_ARTIKEL_ID = "artikel_id"
SCHLUESSEL_ITEM_ID = "item_id"
SCHLUESSEL_GILDEN_NAME = "gilden_name"
SCHLUESSEL_GILDEN_ID = "gilden_id"
SCHLUESSEL_BESCHREIBUNG = "beschreibung"
SCHLUESSEL_STEUER = "steuer"
SCHLUESSEL_ZIEL_ID = "ziel_charakter_id"
SCHLUESSEL_RANG = "rang"